# Generated by Django 4.2.7 on 2023-12-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в  Telegram', unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, help_text='username пользователя в Telegram', max_length=120, null=True, verbose_name='username пользователя')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя в Telegram', max_length=120, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя в Telegram', max_length=120, null=True, verbose_name='Фамилия пользователя')),
                ('language_code', models.CharField(blank=True, help_text='Языка пользователя в Telegram', max_length=120, null=True, verbose_name='Код языка')),
                ('is_bot', models.BooleanField(default=False, help_text='Текст, обозначающий является ли пользователем ботом', verbose_name='Бот')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TryTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=10, help_text='Попытки', verbose_name='Попытки')),
                ('tuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попыткя преобразования',
                'verbose_name_plural': 'Попытки преобразования',
            },
        ),
    ]
