# Generated by Django 4.2.7 on 2023-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_to_speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст, который хотите преобразовать в текст', max_length=600, verbose_name='Текст')),
                ('file_name', models.CharField(max_length=20, verbose_name='Название текста')),
                ('path_file', models.FileField(upload_to='voice/', verbose_name='Ссылка на запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста в речь',
            },
        ),
    ]
